#!/bin/bash

go run ../.. agency start \
--steward-wallet-name "sovrin_steward_wallet" \
--steward-wallet-key "steward_wallet_key" \
--pool-name "FINDY_MEM_LEDGER" \
--steward-did "Th7MpTaRZVRYnPiabds81Y" \
--handshake-register-filepath "findy.json" \
--host-address "localhost"


