#!/bin/bash

set -e

debug=${1:-""}
cli=${FCLI:-findy-agent-cli}

location=$(dirname "$BASH_SOURCE")
[[ "$debug" != "" ]] && echo "location: $location"

source "$location"/name.sh
name=$(calc_name "$debug")

jwt_place="$location"/jwt
jwt=$($jwt_place)

if [[ ! -z $1 ]]; then
	invitation=$(cat "$1")
else
	invitation=${@:-$(cat)}
fi

# conn_id=$(echo $invitation | jq -r '."@id"')

conn_id=$($cli agent connect --jwt "$jwt" --invitation "$invitation")

echo $conn_id

conn_location="$location/$conn_id"
mkdir -p "$conn_location"
echo -n "$invitation" > "$conn_location/invitation.json"

cat > "$conn_location/cfg.yaml" <<EOF
jwt: "$jwt"
conn-id: "$conn_id"
EOF

