#!/bin/bash

set -e

debug=${1:-""}
cli=${FCLI:-findy-agent-cli}

location=$(dirname "$BASH_SOURCE")
[[ "$debug" != "" ]] && echo "location: $location"

source "$location"/name.sh
name=$(calc_name "$debug")
token_place="$location"/token

if [[ -f "$token_place" && $(cat "$token_place") != "" ]]; then
	[[ "$debug" != "" ]] && echo "login with token_place: $token_place"
	jwt=$(cat "$token_place")
else
	[[ "$debug" != "" ]] && echo "login with name: $name"
	jwt=$($cli authn login -u "$name")
fi

echo -n "$jwt" > "$token_place"

conn_location="$location"/"$conn_id"
mkdir -p "$conn_location"

cat > "$location"/cfg.yaml <<EOF
jwt: "$jwt"
EOF

echo "$jwt"

