#!/bin/bash

set -e

debug=${1:-""}
location=$(dirname "$BASH_SOURCE")
[[ "$debug" != "" ]] && echo "location: $location"

source "$location"/name.sh

name=$(calc_name)
jwt_place="$location"/jwt

cli=${FCLI:-findy-agent-cli}
jwt=$($jwt_place)

if [[ "$jwt" != "" ]]; then
	echo "Login OK"
else
	echo "Login error"
fi

