#!/bin/bash

set -e

debug=${1:-""}
cli=${FCLI:-findy-agent-cli}

location=$(dirname "$BASH_SOURCE")
[[ "$debug" != "" ]] && echo "location: $location"

source "$location"/name.sh
name=$(calc_name "$debug") # not used at the moment

token_place="$location"/token
cfg_place="$location"/cfg.yaml

if [ -f "$token_place" ]; then
	rm "$token_place"
	rm "$cfg_place"
	echo "Logout OK"
fi
