#!/bin/bash

if [[ $_ == $0 ]]; then
    printf "Usage:\tsource ""$0"
    printf " [schema_id]\n\n"

    printf "Default schema_id = FCLI_SCHEMA_ID\n"
    exit 1
fi

FCLI_SCHEMA_ID=${1:-$FCLI_SCHEMA_ID}

if [[ $FCLI_SCHEMA_ID == "" ]]; then
	printf "Missing arg [schema_id] or env FCLI_SCHEMA_ID\n"
else
	cli=${FCLI:-findy-agent-cli}

	tag_name=`cli agent ping | sed -E 's/(^.*)(: )(.*$)/\3/g'`
	tag_name="$tag_name""'s_tag"
	epoc=`date +%s`
	tag_name="$tag_name""_""$epoc"
	echo "Creating cred_def: '""$tag_name""' please wait.."

	export FCLI_CRED_DEF_ID=`$cli agent create-cred-def -t TAG -i "$FCLI_SCHEMA_ID"`
fi
