#!/bin/bash

if [[ $_ == $0 ]]; then
    printf "Usage:\tsource ""$0"
    printf " [attr_1 attr_2 ... attr_n]\n\n"

    printf "Default attrs: name gender tel email\n"
    exit 1
fi

cli=${FCLI:-findy-agent-cli}
schema_name=`$cli agent ping | sed -E 's/(^.*)(: )(.*$)/\3/g'`
schema_name="$schema_name""_s_schema"
echo "$schema_name"
version=`date +%s`
version="$version.0"
echo "$version"

if [[ "$1" == "" ]]; then
	export FCLI_SCHEMA_ID=`$cli agent create-schema --name "$schema_name" --version "$version" name gender tel email`
else
	export FCLI_SCHEMA_ID=`$cli agent create-schema --name "$schema_name" --version "$version" $@`
fi

